name: 🚀 Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 📚 Code Checkout
        uses: actions/checkout@v4

      - name: 🚀 Release
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          manifest-file: release.manifest.json
          config-file: release.config.json

    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
      created_tag: ${{ steps.rp.outputs.tag_name }}
