targets:
  $default:
    builders:
      # https://pub.dev/packages/freezed
      freezed:
        options:
          to_json: false
          copy_with: false
          equal: true

      # https://pub.dev/packages/json_serializable
      json_serializable:
        options:
          explicit_to_json: true
          # field_rename: snake
