name: {{import-alias.snakeCase()}}
description: {{{desc}}}
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter

  # router
  go_router: ^14.8.1

  # freezed
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # service locator
  injectable: ^2.5.0
  get_it: ^8.0.3

  # riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # build
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  go_router_builder: ^2.8.2
  build_verify: ^3.1.0
  riverpod_generator: ^2.6.5

  # gitlint
  commitlint_cli: ^0.8.1
  husky: ^0.1.7
  danger_core: ^2.0.0

flutter:
  uses-material-design: true
